apiVersion: v1
kind: Service # menentukan jenis objek yang akan didefinisikan
metadata: # mendefinisikan metadata terkait objek
  labels:
    app: shipping-service
  name: shipping-service
  namespace: e-commerce
spec: # memberikan spesifikasi untuk layanan
  type: ClusterIP  # Mengubah tipe layanan menjadi NodePort supaya dapat diakses melalui port di node
  ports:
  - port: 91
    targetPort: 3001
  selector: # Menentukan selektor yang akan digunakan untuk menemukan pod yang terkait
    app: shipping-service