apiVersion: v1
kind: Service # menentukan jenis objek yang akan didefinisikan
metadata: # mendefinisikan metadata terkait objek
  labels:
    app: order-service
  name: order-service
  namespace: e-commerce
spec:  # memberikan spesifikasi untuk layanan
  type: ClusterIP   # Mengubah tipe layanan menjadi ClusterIP supaya dapat diakses rabbitmq
  ports:
  - port: 90
    targetPort: 3000
  selector: # Menentukan selektor yang akan digunakan untuk menemukan pod yang terkait
    app: order-service