name: CI for karsajobs  # Nama dari GitHub Actions workflow, bisa diganti sesuai kebutuhan Anda.

on:
  push:
    branches:
      - karsajobs  # Aksi ini akan dijalankan saat ada push ke branch dengan nama 'karsajobs'.

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Mengambil kode repositori ke runner.

      - name: Install hadolint
        run: |
          wget https://github.com/hadolint/hadolint/releases/download/v2.7.0/hadolint-Linux-x86_64
          chmod +x hadolint-Linux-x86_64
          sudo mv hadolint-Linux-x86_64 /usr/local/bin/hadolint
        shell: bash  # Menjalankan perintah bash untuk mengunduh dan menginstal hadolint.

      - name: Lint Dockerfile
        run: hadolint Dockerfile  # Menjalankan hadolint untuk memeriksa Dockerfile Anda.

  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Mengambil kode repositori ke runner.

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x  # Mengatur versi Go yang akan digunakan.

      - name: Install dependencies
        run: go mod download  # Menginstal dependensi Go.

      - name: Run unit tests
        run: go test -v -short --count=1 $(go list ./...)  # Menjalankan unit tests Go.

  build-app-karsajobs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Mengambil kode repositori ke runner.

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        # Menggunakan token GitHub untuk login ke GitHub Container Registry.

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/karsajobs-backend:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository }}/karsajobs-backend:${{ github.sha }}
        # Membuild Docker image dan mem-push-nya ke GitHub Container Registry.
